### ISSUE TITLE
Training a general version?

### ISSUE THREAD

**Issue by youssefabdelm** [wpeebles/G.pt#1]
First of all, one of the most impressive research projects I've ever come across. Thank you for being so cool! 

Second, I'm very curious if it's possible to train a general version of G.pt, so maybe take all the models on huggingface and dump them in + as many other datasets as possible. 

Would G.pt as it is now be useful for optimizing, say, a language model or some domain it wasn't trained on?

**Comment by wpeebles** [comment]
Hi @youssefabdelm, thanks for the generous comment. We think multi-task/architecture G.pt models are definitely a cool direction to explore. There would probably need to be a handful of changes to the current model to support multi-architecture training (mainly replacing the per-token encoder/decoders). It'll be cool to see what generalization properties could emerge in a model trained with a sufficiently large and diverse dataset of checkpoints!

**Comment by youssefabdelm** [comment]
Hey @wpeebles I couldn't agree more, thank you for the enlightening answer! I saw the project page but I'll dig more into the paper, it's fascinating to think about just how far it can go. I feel like the implications of a general version of this for large models in particular are tremendous.
