### ISSUE TITLE
question about checkpoints generation

### ISSUE THREAD

**Issue by yeyn19** [wpeebles/G.pt#3]
hello, this is one of the best projects I have ever seen.
I have some questions about the generation of the pretraining data. Let's say MNIST,  for each run, we select 200 checkpoints to save. In the paper I can see "and we randomly save a subset of checkpoints from each training run".
So my question is: does "random" means the random between training steps? And I am also curious about the ratio of saving(200/(25*steps_one_epoch)).  Do you try to save more or less ratio of data, and does the saving ratio influence the performance?

**Comment by wpeebles** [comment]
Hi @yeyn19, thanks for the questions. We used the following methodology to save checkpoints across experiments:

(1) save an initial checkpoint before any training (randomly-initialized parameters)
(2) save the final checkpoint at the very end of training
(3) save the remaining 198 checkpoints by uniformly sampling iterations. 

This is how we implement (3):
```python
import numpy as np
candidate_iters = np.arange(1, total_iters)
rand_iters = np.random.choice(candidate_iters, size=198, replace=False)
```
where `total_iters` is the total number of training steps we take when training a single MNIST/CIFAR-10 model. 

We actually didn't experiment that much with the percentage of checkpoints saved. We have an ablation in our paper (sec 4.6) where we only train on the initial and final checkpoints from each run as opposed to all 200. That seemed to degrade performance quite a lot, so there does seem to be benefit it saving more than the bare-minimum number of checkpoints, but  the optimal ratio is definitely still an open research question! Does this help answer your question?

**Comment by yeyn19** [comment]
thanks a lot!
